CREATE DATABASE sandbox;
GO

USE sandbox;
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Numbers](
	[id] [int] NOT NULL,
	[value1] [int] NULL,
	[value2] [int] NULL,
	[result] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Numbers] ADD PRIMARY KEY CLUSTERED
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[AddNumbers]
    @a INT,
    @b INT,
    @sum INT OUTPUT
AS
BEGIN
    SET @sum = @a + @b;
END;
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   FUNCTION [dbo].[GetNumberById](@Id INT)
RETURNS TABLE
AS
RETURN
(
    SELECT id, value1, value2
    FROM Numbers
    WHERE id = @Id
);
GO
